#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  OvrHead — one-shot Matebook (or any Linux/macOS) setup.
#
#  Run once after cloning/pulling the repo. Does everything:
#    - creates a Python venv + installs deps
#    - creates ~/data/ovrhead-warehouse/
#    - prompts (silently) for OpenSky + Anthropic credentials
#      → writes them to ~/.config/ovrhead/env (mode 600), NEVER to git
#    - creates ~/bin/ovrhead-daily.sh cron wrapper (pull-rebase safe)
#    - installs the cron entry (04:00 UTC daily) if you want it
#    - smoke-tests: pulls one day of OpenSky, one month of Eurostat
#
#  Idempotent: safe to re-run.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

REPO="${REPO:-$HOME/Documents/GitHub/flight-macro}"
ENV_FILE="$HOME/.config/ovrhead/env"
WRAPPER="$HOME/bin/ovrhead-daily.sh"
LOG_DIR="$HOME/data/ovrhead-warehouse"
LOG_FILE="$LOG_DIR/pipeline.log"

if [ ! -d "$REPO" ]; then
    echo "! Repo not found at $REPO"
    echo "  Set REPO=... and re-run, or clone it there first:"
    echo "  git clone <your-repo-url> \"$REPO\""
    exit 1
fi
cd "$REPO"

echo "═══════════════════════════════════════════════════════════════"
echo "  OvrHead — Matebook setup"
echo "  repo:  $REPO"
echo "  env:   $ENV_FILE"
echo "═══════════════════════════════════════════════════════════════"

# ── 1. venv + deps ──────────────────────────────────────────────────
if [ ! -d ".venv" ]; then
    echo "→ Creating venv (.venv)…"
    python3 -m venv .venv
fi
# shellcheck disable=SC1091
source .venv/bin/activate
python3 -m pip install --quiet --upgrade pip
python3 -m pip install --quiet -r scripts/requirements.txt
echo "  ✓ deps installed ($(python3 --version))"

# ── 2. warehouse dir ────────────────────────────────────────────────
mkdir -p "$LOG_DIR" "$HOME/data/ovrhead-warehouse/raw/opensky" \
         "$HOME/data/ovrhead-warehouse/raw/eurostat" \
         "$HOME/data/ovrhead-warehouse/curated" \
         "$HOME/bin" "$(dirname "$ENV_FILE")"
echo "  ✓ warehouse: $HOME/data/ovrhead-warehouse/"

# ── 3. credentials (silent prompt, written to ~/.config, mode 600) ──
touch "$ENV_FILE"; chmod 600 "$ENV_FILE"

get_or_prompt() {
    local key="$1" prompt="$2" existing
    existing=$(grep -E "^${key}=" "$ENV_FILE" 2>/dev/null | tail -1 | cut -d= -f2- || true)
    if [ -n "$existing" ]; then
        echo "  ✓ $key already set (unchanged; delete from $ENV_FILE to reset)"
        return
    fi
    read -srp "  $prompt: " val; echo
    if [ -n "$val" ]; then
        # remove old, append new
        grep -v "^${key}=" "$ENV_FILE" > "$ENV_FILE.tmp" 2>/dev/null || true
        echo "${key}=${val}" >> "$ENV_FILE.tmp"
        mv "$ENV_FILE.tmp" "$ENV_FILE"
        chmod 600 "$ENV_FILE"
        echo "  ✓ $key stored"
    else
        echo "  · $key skipped (empty)"
    fi
}
echo ""
echo "── OpenSky Network (sign up first: https://opensky-network.org) ──"
echo "  (create an API client at https://opensky-network.org → Account → API Client)"
get_or_prompt "OPENSKY_CLIENT_ID" "OpenSky client_id (press Enter to skip)"
get_or_prompt "OPENSKY_CLIENT_SECRET" "OpenSky client_secret (hidden; press Enter to skip)"
echo ""
echo "── Anthropic (optional; needed for Claude enrichment) ──"
get_or_prompt "ANTHROPIC_API_KEY" "Anthropic API key (hidden; press Enter to skip)"

# ── 4. daily wrapper (loads creds, pulls-rebase, runs pipeline, pushes) ─
cat > "$WRAPPER" <<WRAPPER_EOF
#!/usr/bin/env bash
# Auto-generated by scripts/bootstrap_matebook.sh — safe to re-run bootstrap.
set -eu
export PATH="/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:\$PATH"
REPO="$REPO"
LOG="$LOG_FILE"

# load credentials (never committed)
if [ -f "$ENV_FILE" ]; then
    set -a; . "$ENV_FILE"; set +a
fi

cd "\$REPO"

# Sync with remote before doing anything — if the Mac session pushed code
# changes, rebase on top of them so our data-only push won't conflict.
git pull --rebase --autostash origin main >> "\$LOG" 2>&1 || {
    echo "\$(date -u +%FT%TZ) [git] pull-rebase failed; aborting to avoid mess" >> "\$LOG"
    exit 1
}

source .venv/bin/activate

# Fetch fresh OpenSky (last 14 days rolling window). If OPENSKY_CLIENT_ID is unset,
# the script exits cleanly with a message — no harm.
python3 scripts/fetch_opensky_now.py --days 14 >> "\$LOG" 2>&1 || \
    echo "\$(date -u +%FT%TZ) [opensky] fetch failed (non-fatal)" >> "\$LOG"

# Commit + push if the JSON actually changed
if ! git diff --quiet data/insights.json; then
    git add data/insights.json
    git commit -m "chore(data): daily refresh \$(date -u +%F)" >> "\$LOG" 2>&1
    git push origin main >> "\$LOG" 2>&1 && \
        echo "\$(date -u +%FT%TZ) [git] pushed data update" >> "\$LOG"
else
    echo "\$(date -u +%FT%TZ) [ok] no data change" >> "\$LOG"
fi
WRAPPER_EOF
chmod +x "$WRAPPER"
echo "  ✓ wrapper: $WRAPPER"

# ── 5. offer to install cron ────────────────────────────────────────
echo ""
read -rp "Install daily cron (04:00 UTC every day)? [y/N] " install_cron
if [[ "${install_cron:-}" =~ ^[Yy]$ ]]; then
    LINE="0 4 * * * $WRAPPER"
    (crontab -l 2>/dev/null | grep -v "$WRAPPER" ; echo "$LINE") | crontab -
    echo "  ✓ cron installed:  $LINE"
    echo "  view:  crontab -l"
    echo "  logs:  tail -f $LOG_FILE"
else
    echo "  · skipped. To install later:"
    echo "    (crontab -l; echo '0 4 * * * $WRAPPER') | crontab -"
fi

# ── 6. smoke test ───────────────────────────────────────────────────
echo ""
read -rp "Run a smoke test now (fetches 1 day OpenSky + 1 month Eurostat, ~4 min)? [y/N] " smoke
if [[ "${smoke:-}" =~ ^[Yy]$ ]]; then
    set +e
    set -a; . "$ENV_FILE"; set +a
    if [ -n "${OPENSKY_CLIENT_ID:-}" ]; then
        echo "→ OpenSky: yesterday, 30 hubs…"
        python3 scripts/fetch_opensky_now.py --days 1 2>&1 | tail -8
    else
        echo "· OpenSky creds not set — skipping OpenSky smoke test."
    fi
    echo "→ Eurostat: Oct 2024, 3 reporters…"
    python3 scripts/fetch_real_now.py --month 2024-10 --top 20 --top-city 40 2>&1 | tail -6
    set -e
fi

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  Done. What just happened:"
echo "  · venv:      $REPO/.venv"
echo "  · creds:     $ENV_FILE  (mode 600, never in git)"
echo "  · wrapper:   $WRAPPER"
echo "  · warehouse: $LOG_DIR"
echo "  · logs:      tail -f $LOG_FILE"
echo "═══════════════════════════════════════════════════════════════"
